[package]
org = "AnjanaSPorawagama"
name = "Component_E"
version = "1.0.0"
export = ["Component_E"]
distribution = "2201.3.1"
keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
icon = "docs/icon.png"

[build-options]
observabilityIncluded = true
